services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_board_scheduler
    restart: unless-stopped
    command: ["python", "-u", "scheduler_daemon.py"]
    environment:
      - IS_DR_NODE=True
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_board_bot
    restart: unless-stopped
    command: ["python", "-u", "bot_daemon.py"]
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
