services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_board_scheduler
    restart: unless-stopped
    command: ["python", "-u", "scheduler_daemon.py"]
    env_file:
      - .env
    environment:
      - IS_DR_NODE=True
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_board_bot
    restart: unless-stopped
    command: ["python", "-u", "bot_daemon.py"]
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
