version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_board_web
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - PORT=5001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_board_scheduler
    restart: unless-stopped
    command: ["python", "scheduler_daemon.py"]
    environment:
      - IS_DR_NODE=True
    volumes:
      - ./.env:/app/.env:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
